export default buddyData = [{
    "id": 1,
    "first_name": "Colby",
    "last_name": "Haddleston",
    "gender": "Male",
    "social_style": "Down-sized",
    "availability": "Monthly"
  }, {
    "id": 2,
    "first_name": "Baxter",
    "last_name": "Treverton",
    "gender": "Male",
    "social_style": "human-resource",
    "availability": "Yearly"
  }, {
    "id": 3,
    "first_name": "Gordy",
    "last_name": "De la Zenne",
    "gender": "Male",
    "social_style": "Down-sized",
    "availability": "Seldom"
  }, {
    "id": 4,
    "first_name": "Lief",
    "last_name": "Rapp",
    "gender": "Male",
    "social_style": "zero defect",
    "availability": "Weekly"
  }, {
    "id": 5,
    "first_name": "Perren",
    "last_name": "Broadhurst",
    "gender": "Male",
    "social_style": "content-based",
    "availability": "Seldom"
  }, {
    "id": 6,
    "first_name": "Wendel",
    "last_name": "Cristoferi",
    "gender": "Male",
    "social_style": "Advanced",
    "availability": "Never"
  }, {
    "id": 7,
    "first_name": "Farlay",
    "last_name": "Wane",
    "gender": "Male",
    "social_style": "project",
    "availability": "Often"
  }, {
    "id": 8,
    "first_name": "Allissa",
    "last_name": "Tampling",
    "gender": "Female",
    "social_style": "Quality-focused",
    "availability": "Seldom"
  }, {
    "id": 9,
    "first_name": "Cos",
    "last_name": "Di Antonio",
    "gender": "Male",
    "social_style": "Persistent",
    "availability": "Yearly"
  }, {
    "id": 10,
    "first_name": "Andrej",
    "last_name": "Blowick",
    "gender": "Male",
    "social_style": "human-resource",
    "availability": "Often"
  }]