export default volunteerData = [{
    "id": 1,
    "first_name": "Mara",
    "last_name": "Plunket",
    "gender": "Female",
    "social_style": "Team-oriented",
    "availability": "Often"
  }, {
    "id": 2,
    "first_name": "Harriott",
    "last_name": "McGenn",
    "gender": "Female",
    "social_style": "Robust",
    "availability": "Seldom"
  }, {
    "id": 3,
    "first_name": "Ronalda",
    "last_name": "Prestedge",
    "gender": "Female",
    "social_style": "background",
    "availability": "Once"
  }, {
    "id": 4,
    "first_name": "Chariot",
    "last_name": "Gencke",
    "gender": "Male",
    "social_style": "initiative",
    "availability": "Never"
  }, {
    "id": 5,
    "first_name": "Marji",
    "last_name": "Bulfit",
    "gender": "Female",
    "social_style": "implementation",
    "availability": "Seldom"
  }, {
    "id": 6,
    "first_name": "Prudy",
    "last_name": "Elves",
    "gender": "Female",
    "social_style": "upward-trending",
    "availability": "Once"
  }, {
    "id": 7,
    "first_name": "Hershel",
    "last_name": "Grace",
    "gender": "Male",
    "social_style": "secured line",
    "availability": "Monthly"
  }, {
    "id": 8,
    "first_name": "Adam",
    "last_name": "Wittier",
    "gender": "Male",
    "social_style": "encryption",
    "availability": "Often"
  }, {
    "id": 9,
    "first_name": "Laurent",
    "last_name": "Jagson",
    "gender": "Male",
    "social_style": "strategy",
    "availability": "Once"
  }, {
    "id": 10,
    "first_name": "Hammad",
    "last_name": "Frid",
    "gender": "Male",
    "social_style": "reciprocal",
    "availability": "Yearly"
  }]