export default volunteerData = [{
  "id": 1,
  "first_name": "Crosby",
  "last_name": "Wogan",
  "gender": "Male",
  "social_style": "client-driven",
  "availability": "Seldom"
}, {
  "id": 2,
  "first_name": "Granger",
  "last_name": "Tremmil",
  "gender": "Male",
  "social_style": "Quality-focused",
  "availability": "Daily"
}, {
  "id": 3,
  "first_name": "Jacinthe",
  "last_name": "Sakins",
  "gender": "Female",
  "social_style": "approach",
  "availability": "Often"
}, {
  "id": 4,
  "first_name": "Brita",
  "last_name": "Josefovic",
  "gender": "Female",
  "social_style": "open system",
  "availability": "Never"
}, {
  "id": 5,
  "first_name": "Florry",
  "last_name": "Pidduck",
  "gender": "Female",
  "social_style": "system-worthy",
  "availability": "Yearly"
}, {
  "id": 6,
  "first_name": "Vilma",
  "last_name": "Jehaes",
  "gender": "Female",
  "social_style": "Compatible",
  "availability": "Never"
}, {
  "id": 7,
  "first_name": "Ashely",
  "last_name": "Castanyer",
  "gender": "Female",
  "social_style": "Horizontal",
  "availability": "Often"
}, {
  "id": 8,
  "first_name": "Lorita",
  "last_name": "Caesman",
  "gender": "Female",
  "social_style": "collaboration",
  "availability": "Seldom"
}, {
  "id": 9,
  "first_name": "Aura",
  "last_name": "Kaubisch",
  "gender": "Female",
  "social_style": "info-mediaries",
  "availability": "Yearly"
}, {
  "id": 10,
  "first_name": "Ban",
  "last_name": "Branney",
  "gender": "Male",
  "social_style": "context-sensitive",
  "availability": "Weekly"
}]